# Generated by Django 3.2.4 on 2021-06-17 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FTL_Game_Updates',
            new_name='Community_Announcement',
        ),
        migrations.RenameModel(
            old_name='Community_Guides',
            new_name='Community_Guide',
        ),
        migrations.RenameModel(
            old_name='FTL_Systems',
            new_name='FTL_Augment',
        ),
        migrations.RenameModel(
            old_name='Community_Announcements',
            new_name='FTL_Game_Update',
        ),
        migrations.RenameModel(
            old_name='FTL_Ships',
            new_name='FTL_Ship',
        ),
        migrations.RenameModel(
            old_name='FTL_Augments',
            new_name='FTL_System',
        ),
        migrations.RenameModel(
            old_name='FTL_Weapons',
            new_name='FTL_Weapon',
        ),
        migrations.RenameModel(
            old_name='User_Submitted_Runs',
            new_name='User_Submitted_Run',
        ),
    ]
