# Generated by Django 3.2.4 on 2021-06-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_db', '0002_auto_20210617_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_submitted_run',
            name='difficulty',
            field=models.CharField(choices=[('H', 'Hard'), ('N', 'Normal'), ('E', 'Easy')], default='N', max_length=1),
        ),
    ]
