# Generated by Django 3.2.4 on 2021-06-18 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_db', '0003_user_submitted_run_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_submitted_run',
            name='ship_name',
        ),
        migrations.AddField(
            model_name='user_submitted_run',
            name='ship_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_db.ftl_ship'),
        ),
        migrations.AlterField(
            model_name='ftl_ship',
            name='designation',
            field=models.CharField(default='Unknown Ship', max_length=20),
        ),
    ]
